### ISSUE TITLE
Malfunction in display negative values

### ISSUE THREAD

**Issue by iulian34** [bbonnin/vue-morris#10]
Hello,
It seems that the bar graph on several negative values is wrong.
```
"testChart": [
{
"totalProfit": -956,
"month": "January"
},
{
"totalProfit": -400,
"month": "February"
}
],
```
![screenshot-2018-2-5 http cota2 test](https://user-images.githubusercontent.com/7355974/35811992-7df2a85a-0a98-11e8-8f64-a6b6d9f7301e.png)

**Comment by iulian34** [comment]
Can you please tell me if I'm doing something wrong or is a bug?
Thank you.

**Comment by bbonnin** [comment]
Can you provide more details about the configuration of the chart ? Thanks !

**Comment by iulian34** [comment]
```
<bar-chart
                id="bar" :data="testChart" xkey="month" ykeys='[ "totalProfit"]' resize="true"
                labels='[ "Total profit"]' :bar-colors="osColor"
                grid="true" grid-text-weight="bold" hide-hover="auto">
</bar-chart>
```

**Comment by bbonnin** [comment]
Hello,
I have updated the component: the last version (0.0.13) includes a fix for your problem.
Your problem only occurs if all values are negative.
If your are sure that you have only negative values, just add a new attribute: `ymax="0"`
This will force the bar chart to star the y axis to start at 0.
You will get somthing like this:
![vue-morris-negative-values](https://user-images.githubusercontent.com/1908593/36074363-71976342-0f3f-11e8-87a4-5475bad369ca.png)

**Comment by iulian34** [comment]
Hello, 

Attribute ymax="0" is doing the trick for all negative values but I have situation when I have negative and positive values and this thing is not gone work. Can be implement as function when all the values are negative to bind this attribute ymax="0"? 

Thank you
