### ISSUE TITLE
Getting 'define is not defined' Error

### ISSUE THREAD

**Issue by thukuwanjiku** [bbonnin/vue-morris#13]
Hello, I think vue-morris is awesome, however I tried it and it never went past the error. Please check if I did any error here 
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3k7vw1yjw)

**Comment by bbonnin** [comment]
Hello,

Have you tried the project https://github.com/bbonnin/vue-morris-example ?
It gives some examples on how to use this lib.

**Comment by thukuwanjiku** [comment]
I think the problem was with Codesandbox then, cos I first cloned your example onto my local environment and it worked, then I copy-pasted the example I had tried on Codesandbox, and it also worked. 

Thanks alot @bbonnin
