### ISSUE TITLE
Adding option 'yLabelFormat' in BarChart?

### ISSUE THREAD

**Issue by aria-grande** [bbonnin/vue-morris#14]
Hi, thank you for making this library. I'm using it well.
Why don't you add an option `yLabelFormat` in BarChart?
Find more in https://codepen.io/andreic/pen/olzAJ

**Comment by bbonnin** [comment]
Hi,
You're right, I have forgotten to add these options (y and xLabelFormat).
I've published the version 1.0.0 with these options for bar chart.
Thank you !
