### ISSUE TITLE
Outdated jQuery Dependency

### ISSUE THREAD

**Issue by purplelady105** [bbonnin/vue-morris#16]
Version 1.0.1 has a dependency of jquery version 2.2.4, however, jquery is vulnerable to cross-site scripting attacks if using anything older than version 3.0.0 as per this security advisory: https://www.npmjs.com/advisories/328

Can you update the dependencies to require jquery version 3.0.0 or later? As of now, the latest is version 3.3.1

**Comment by pierresh** [comment]
No need [to use jQuery](https://pierresh.github.io/morris.js/) 😃

**Comment by purplelady105** [comment]
> No need [to use jQuery](https://pierresh.github.io/morris.js/) 😃

lol I found that out a month after posting this 😆 I was super excited to prune that out.
