### ISSUE TITLE
x-label-angle not working in bar-chart

### ISSUE THREAD

**Issue by ccorreia-multiconversion** [bbonnin/vue-morris#22]
Hi, the property xLabelAngle is not working, it is displayed in horizontal format
Here is my code

`<bar-chart
            v-if="show"
            style="height: 558px;padding-bottom: 30px;"
            id="hashtagChart"
            grid="false"
            :data='metrics'
            xkey="label"
            x-label-angle="45"
            ykeys='[ "impressions", "average" ]'
            labels='[ "Impressions", "Media" ]'
            bar-colors='[ "#1D71BC", "#2C9EFF" ]'>
        </bar-chart>
`

On the version of morris with jquery, the angle is working

Sorry for my english!

**Comment by bbonnin** [comment]
Hi,
Thanks for reporting this issue!
Fix in v1.0.2
