### ISSUE TITLE
yMin and yMax not working

### ISSUE THREAD

**Issue by ccorreia-multiconversion** [bbonnin/vue-morris#24]
Hi again!

These properties are not working in area-chart, never call the function getMin and getMax

`:yMin="getMin"
:yMax="getMax"`

On the version of morris with jquery, thhese properties are working.

Sorry again for my english!
Thx

**Comment by bbonnin** [comment]
Hi,
First, the option names: `ymin` and `ymax` (without uppercase).
Then, I haven't seen in Morris.js code that these options can be used as functions (maybe I am wrong).
Can you provide me an example (without vue-morris) where you set these options as functions.
Thanks :)

**Comment by ccorreia-multiconversion** [comment]
Hi, sorry for the delay, here is the code

[https://jsfiddle.net/ccorreia64/f5097zmu/](https://jsfiddle.net/ccorreia64/f5097zmu/)

**Comment by bbonnin** [comment]
Hi,
I understand your example. 
I have updated my project `vue-morris-example` to show you how to get your example working with `vue-morris`.
For short:
* `ymin` and  `ymax` can not be functions
* you can use computed properties to get the values for `ymin` and  `ymax`

Check this file: https://github.com/bbonnin/vue-morris-example/blob/master/src/App.vue
The last chart is your chart (with less data :) ) and you could see how to do with `vue-morris` in your context.
