### ISSUE TITLE
How can acces to method redraw?

### ISSUE THREAD

**Issue by ccorreia-multiconversion** [bbonnin/vue-morris#25]
Hi!

I have the followed graph

![image](https://user-images.githubusercontent.com/48756697/64111098-20bac900-cd84-11e9-84d0-5158cd6082cb.png)

And added ref="graph"

when access this.$refs.graph.redraw() throw an error this.$ref.graph.redraw is not a function

**Comment by bbonnin** [comment]
Hi,

I think you should try something like: `this.$refs.graph.chart.redraw()`.
* `this.$refs.graph` returns the component
* `this.$refs.graph.chart` returns the data named `chart` in the component (that is an instance of the Morris object)
