### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by yuredev** [bbonnin/vue-morris#28]
i´m trying to build chart, but i got "jQuery is not defined" in the console error. How i can add jQuery? i would be very happy if someone help me.

**Comment by bbonnin** [comment]
Hello,

Take a look at the example project: https://github.com/bbonnin/vue-morris-example
In webpack.config.js, there is a reference to JQuery, so it can be used.

**Comment by yuredev** [comment]
I did it, thanks
