### ISSUE TITLE
Custom formatter function?

### ISSUE THREAD

**Issue by LaurierMantel** [bbonnin/vue-morris#29]
I am building a Donut chart and would like to be able to pass a custom formatter function. I would like to be able to pass a function that takes in a string value and reformats it (for instance, adding a `%` symbol:
Is there a way to do this?
@bbonnin 

<img width="330" alt="image" src="https://user-images.githubusercontent.com/9892964/75099572-07971600-5578-11ea-99c7-6805fdebc180.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/9892964/75099549-dc142b80-5577-11ea-9955-5cb4416a7503.png">

**Comment by LaurierMantel** [comment]
RESOLVED:
```

<template>
  <div>
    <div class="col-md-4">
      <donut 
        id="pie"
        :data="donutData"
        colors='["#FF6384", "#36A2EB", "#FFFF11"]'
        resize="True"
        :formatter="this.formatFunc"
      >
      </donut>
    </div>
    <div class="col-md-6">
    </div>
  </div>
</template>

<script>

  import { DonutChart } from 'vue-morris'
  export default {
    methods: {
      formatFunc: function(string) {
        return string + "%"
      }
    },
    components: {
      'donut': DonutChart
    },
    props: ['activity'],
    computed: {
      donutData: function () {

        return [
          { label: 'Percent One', value: 60 },
          { label: 'Percent Two', value: 10 },
          { label: 'Percent Three', value: 30 }
        ]
      }
    }
  }
</script>
<style>
</style>
```
<img width="309" alt="image" src="https://user-images.githubusercontent.com/9892964/75099656-f6023e00-5578-11ea-855a-fb23c5cff421.png">

**Comment by LaurierMantel** [comment]
@bbonnin is there docs for this (passing formatter function)? It is super useful.

**Comment by bruno-bonnin-cbp** [comment]
Hello,

As `vue-morris` is just a wrapper, so you can look at the official documentation of Morris.js.
Sometimes, I put some examples in [vue-morris-example](https://github.com/bbonnin/vue-morris-example) project.
But, you are right, I should add more docs/examples.
