### ISSUE TITLE
Get rid of jQuery

### ISSUE THREAD

**Issue by Herteby** [bbonnin/vue-morris#5]
Morris.js's dependency on jQuery is ridiculously small and could easily be removed, and I think jQuery is something many people in the Vue community don't want.
There's already a pull request on morris.js: https://github.com/morrisjs/morris.js/pull/503
Sadly morris.js seems abandoned by it's creator, so you would have to move to a fork. I might do it but I'm not really a pro at Git :sweat_smile:

**Comment by pierresh** [comment]
Hello, 

For your information I just published on npm a fork of Morris that has no any jQuery dependency called morris.js06. This also include many new features that did not exist in original morris.js.

You can have a look here: https://www.npmjs.com/package/morris.js06

**Comment by bbonnin** [comment]
Hello,

As the project Morris.js is abandonned, I think it should be a good idea to use your fork.
Have you already done some tests of vue-morris and morris.js06 ?

**Comment by pierresh** [comment]
Hello,

Actually no, I am not a vue.js user ^^. I found this thread from the pull request in the original repository, but I think there should have no any breaking change, I just added some options.
