### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clear' of undefined"

### ISSUE THREAD

**Issue by iulian34** [bbonnin/vue-morris#6]
Hello, 
As title say I get this error and donut chart is not show

**Comment by bbonnin** [comment]
Hello,
Could you provide more information about your context ? Version, code snippets, ...
Thanks !

**Comment by iulian34** [comment]
Hello, 
Thank you for your fast replay. Here is my code

<pre>
<template>
    <div>
        <donut-chart
                id="donut"
                :data="donutData"
                colors='[ "#1ab394", "#ff000a", "#867389"]'
                resize="true">
        </donut-chart>
    </div>
</template>

<script>
    import Raphael from 'raphael/raphael'
    global.Raphael = Raphael
    import {DonutChart} from 'vue-morris'
    export default {
        props: ["profileUserId"],
        components: {
            DonutChart,
        },
        data() {
            return {
                donutData: []
            }
        },
        mounted () {
            this.fetchAllUserStatistics()
        },
        methods: {
            fetchAllUserStatistics() {
                let vm = this
                axios.get('/api/user-statistics/' + this.profileUserId).then(
                    function (response) {
                        vm.donutData = response.data.chartData
                    }
                )
            }
        },
    }
</script>
</pre>
chartData looks like this

[
{
"label": "Test1",
"value": 73
},
{
"label": "Test2",
"value": 71
},
{
"label": "Test3",
"value": 28
}
]

**Comment by bbonnin** [comment]
Thanks for reporting this bug.

**Comment by bbonnin** [comment]
Fix v0.0.10
