### ISSUE TITLE
Other color for negative values

### ISSUE THREAD

**Issue by iulian34** [bbonnin/vue-morris#7]
Hello, 
As title say, any possibility to change color for negative values on Line and Bar charts?

**Comment by bbonnin** [comment]
Hello,
With Morris.js, you need to provide a function instead of an array.
But the wrapper only accepts string or array, not a function :-(
I need to provide a fix for that.

**Comment by bbonnin** [comment]
With v0.0.11, you can use a function for color parameter. Check the content of the `examples` directory.
